In [12]:
import numpy as np

In [13]:
my_list = [1,2,3]

In [15]:
arr = np.array(my_list)

In [16]:
arr

array([1, 2, 3])

In [17]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [26]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [27]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [33]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.random.rand(5)

array([0.63098172, 0.31070068, 0.59510246, 0.87241305, 0.05438897])

In [35]:
np.random.rand(5,5)

array([[0.05829227, 0.28755295, 0.61072312, 0.74232027, 0.12956779],
       [0.2163843 , 0.6421729 , 0.65103812, 0.73502898, 0.36735592],
       [0.99329918, 0.92883592, 0.45467638, 0.56969519, 0.20555665],
       [0.96246702, 0.07178588, 0.26105145, 0.31900253, 0.32555885],
       [0.07301594, 0.96266139, 0.5292444 , 0.18082878, 0.01788731]])

In [36]:
np.random.randn(2)

array([ 0.92566747, -0.75938292])

In [37]:
np.random.randn(4,4)

array([[ 1.9176969 ,  0.02972529,  0.42918628,  0.55849992],
       [-0.62647056,  1.01792386,  2.26868709, -0.35688332],
       [-0.09369368, -1.40021104, -1.75018432,  0.96599705],
       [-0.32654983, -0.4998006 ,  0.36914137,  0.17919391]])

In [38]:
np.random.randint(1,100,12)

array([59,  6, 39, 83, 38, 62, 56, 74, 82, 53, 11, 77])

In [39]:
np.random.randint(1,50,6)

array([11, 40,  9, 15, 34, 15])

In [40]:
arr = np.arange(25)

In [41]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr = np.random.randint(1,50,5)

In [44]:
ranarr


array([37, 32,  9, 32, 16])

In [45]:
ranarr.max()

37

In [46]:
ranarr.min()

9

In [47]:
ranarr.argmax()

0

In [48]:
ranarr.argmin()

2

In [49]:
arr.shape

(25,)

In [50]:
arr.dtype

dtype('int64')

In [52]:
from numpy.random import randint

In [53]:
randint(2,10)

6